### ISSUE TITLE
Error installing torch-cl on Ubuntu 16.04 with Anaconda Python and mainline torch installed

### ISSUE THREAD

**Issue by vinhqdang** [hughperkins/distro#2]
I have Ubuntu 16.04 server, with Anaconda Python 2.7.11 and _mainline_ torch installed and run already (with LUAJIT2.1)

I tried to install torch-cl by following the instruction, but remove libqt4-core and libqt4-gui from install-deps script.

Then I do `./install.sh`

and met

```
./install.sh 
Prefix set to /home/vinh/torch-cl/install
Installing Lua version: LUAJIT21
/home/vinh/anaconda2/lib/libreadline.so: undefined reference to `tputs'
/home/vinh/anaconda2/lib/libreadline.so: undefined reference to `tgoto'
/home/vinh/anaconda2/lib/libreadline.so: undefined reference to `tgetflag'
/home/vinh/anaconda2/lib/libreadline.so: undefined reference to `UP'
/home/vinh/anaconda2/lib/libreadline.so: undefined reference to `tgetent'
/home/vinh/anaconda2/lib/libreadline.so: undefined reference to `tgetnum'
/home/vinh/anaconda2/lib/libreadline.so: undefined reference to `PC'
/home/vinh/anaconda2/lib/libreadline.so: undefined reference to `tgetstr'
/home/vinh/anaconda2/lib/libreadline.so: undefined reference to `BC'
collect2: error: ld returned 1 exit status
make[2]: *** [exe/luajit-rocks/luajit-2.1/luajit] Error 1
make[1]: *** [exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all] Error 2
make: *** [all] Error 2
./install.sh: line 86: /home/vinh/torch-cl/install/bin/luarocks: No such file or directory
Installing common Lua packages
./install.sh: line 90: /home/vinh/torch-cl/install/bin/luarocks: No such file or directory
```

**Comment by hughperkins** [comment]
seems like you're either missing libreadline-dev, or anaconda is overriding it.  I think the first thing to try would be:

```
sudo apt-get install -y libreadline-dev
```

If that doesnt fix it, we may need to remove/replace the libreadline in the anaconda distribution

**Comment by hughperkins** [comment]
(how are you installing anaconda?  I might download it and have a play)

**Comment by vinhqdang** [comment]
Sorry for the later reply, I will try it today and see what happen. 

I installed anaconda from the website:

```
wget http://repo.continuum.io/archive/Anaconda2-4.0.0-Linux-x86_64.sh
chmod +x Anac..
./Ana...
```

**Comment by hughperkins** [comment]
Oh... you're using anaconda just for installation.  Hmmm.  Installation shouldnt even need python/anaconda.  I wasnt really thinking about what you were doing (I have a project [pytorch](https://github.com/hughperkins/pytorch) where people are using python/anaconda, and mixed up the two in my mind).

You shouldnt need python/anaconda in your path at all really.... can you do:

```
echo PATH $PATH
echo LDFLAGS $LDFLAGS
echo LD_LIBRARY_PATH $LD_LIBRARY_PATH
```

and paste the results here?

**Comment by hughperkins** [comment]
(by the way, I tried installing anaconda on my 16.04 box, and running install.sh, and... worked ok for me :-P  So I think we should have the values of the variables above to go further)

**Comment by hughperkins** [comment]
Oh wait, you do need python right?  for the clblas install.  Hmmmm.  But... it installs ok for me, on Ubuntu 16.04.  I think I need more information on the environment variables above, to go further.

**Comment by vinhqdang** [comment]
Well

My Ubuntu 16.04 is quite new, with:
- Anaconda 2
- R 3.2.5
- mainline torch
- git, vim, etc.
  and trying torch-cl

**Comment by vinhqdang** [comment]
Yes, I need Python for other tasks :-)

**Comment by hughperkins** [comment]
Hi.  Do you have any updates or additional information for this?  It works ok on my own ubuntu 16.04, with anaconda, so I'm not sure how I can go further with this without additional information :-)

**Comment by vinhqdang** [comment]
Oops, I am in Windows now and cannot check. Will report soon

**Comment by eneskemalergin** [comment]
@hughperkins hello, I have the same problem and I have installed anaconda2 before trying to install torch7. I guess I messed up with the paths because when I call;

`echo PATH $PATH`

it returned this:

```
PATH /home/enes/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Can you help me with this?

**Comment by hughperkins** [comment]
Well, it looks like `tputs` is some kind of term related function, which is apparently in term.h, or curses.h, but I dont have either of these files on my system.  Can you confirm the results of:

```
dpkg -l '*libreadline*' | grep ii
```

... please

**Comment by eneskemalergin** [comment]
```
ii  libreadline-dev:amd64  6.3-8ubuntu2 amd64        GNU readline and history libraries, development files
ii  libreadline6:amd64     6.3-8ubuntu2 amd64        GNU readline and history libraries, run-time libraries
ii  libreadline6-dev:amd64 6.3-8ubuntu2 amd64        GNU readline and history libraries, development files
```

**Comment by hughperkins** [comment]
Hmmm, identical to myself.... and I'm on ubuntu 16.04 too...

**Comment by eneskemalergin** [comment]
What is your path when you call the `$PATH`?

**Comment by hughperkins** [comment]
```
$ echo $PATH
/myfiles/anaconda2/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by eneskemalergin** [comment]
I guess we have the same path. 

So you directly installed it, and it works, you just did this:

```
git clone --recursive https://github.com/hughperkins/distro -b distro-cl ~/torch-cl
cd ~/torch-cl
bash install-deps
./install.sh
```

right?

**Comment by hughperkins** [comment]
actually, I can reproduce the error...

**Comment by hughperkins** [comment]
Ok. Can you try the following please?

```
cd ~/torch-cl
git pull
rm -Rf build
./install.sh
```

**Comment by eneskemalergin** [comment]
Now I got something like this:

```
Installing Lua version: LUAJIT21
CMake Error at /usr/share/cmake-3.5/Modules/CMakeDetermineCCompiler.cmake:57 (message):
  Could not find compiler set in environment variable CC:

  gcc-4.9.
Call Stack (most recent call first):
  CMakeLists.txt


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

**Comment by hughperkins** [comment]
Hmmm, in theory install-deps should have installed gcc-4.9.  Can you provide the output of the following please :

```
dpkg -l '*gcc*' | grep ii
```

**Comment by eneskemalergin** [comment]
```
ii  gcc                4:5.3.1-1ubuntu1 amd64        GNU C compiler
ii  gcc-5              5.3.1-14ubuntu2  amd64        GNU C compiler
ii  gcc-5-base:amd64   5.3.1-14ubuntu2  amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-6-base:amd64   6.0.1-0ubuntu1   amd64        GCC, the GNU Compiler Collection (base package)
ii  libgcc-5-dev:amd64 5.3.1-14ubuntu2  amd64        GCC support library (development files)
ii  libgcc1:amd64      1:6.0.1-0ubuntu1 amd64        GCC support library
```

**Comment by hughperkins** [comment]
Ok.  Not sure why gcc-4.9 is not installed.  But I think if you do the following, this might fix the current error message:

```
sudo apt-get install -y gcc-4.9 g++-4.9
./install.sh
```

**Comment by eneskemalergin** [comment]
I guess Ubuntu 16.04 is using GCC 5 as default now I am downgrading it. I hope now it will work

**Comment by hughperkins** [comment]
yeah, you might need also:

```
sudo apt-get install -y libgfortran-4.9-dev
```

(By the way, I've updated `install-deps` to hopefully fix this https://github.com/hughperkins/distro-cl/commit/a94a532a1cd4096067684bef9d3a7175f0345d7a

**Comment by manugarri** [comment]
Same issue here, super interested following this thread in real time

 ![](https://66.media.tumblr.com/cde20fc2b5009bf8b18cfdcb8ae5188e/tumblr_noys8mkgT11s0my1wo1_250.gif)

**Comment by hughperkins** [comment]
:-D

**Comment by hughperkins** [comment]
Gotta re-use that png sometime :-D

**Comment by eneskemalergin** [comment]
Exactly!, nice one @manugarri

**Comment by manugarri** [comment]
:)  One diff i see on my machine with @eneskemalergin is the gcc version (i have 4.9)

```
 $ dpkg -l '*gcc*' | grep ii
ii  gcc                  4:5.3.1-1ubuntu1 amd64        GNU C compiler
ii  gcc-4.9              4.9.3-13ubuntu2  amd64        GNU C compiler
ii  gcc-4.9-base:amd64   4.9.3-13ubuntu2  amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-5                5.3.1-14ubuntu2  amd64        GNU C compiler
ii  gcc-5-base:amd64     5.3.1-14ubuntu2  amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-6-base:amd64     6.0.1-0ubuntu1   amd64        GCC, the GNU Compiler Collection (base package)
ii  lib32gcc1            1:6.0.1-0ubuntu1 amd64        GCC support library (32 bit Version)
ii  libgcc-4.9-dev:amd64 4.9.3-13ubuntu2  amd64        GCC support library (development files)
ii  libgcc-5-dev:amd64   5.3.1-14ubuntu2  amd64        GCC support library (development files)
ii  libgcc1:amd64        1:6.0.1-0ubuntu1 amd64        GCC support library
```

**Comment by hughperkins** [comment]
Yup, 4.9 looks good :-)

**Comment by eneskemalergin** [comment]
Something is happening now, I passed the latest errors. Now I will wait, till the end!

**Comment by manugarri** [comment]
waat! What did you do??

**Comment by eneskemalergin** [comment]
I did this:

```
cd ~/torch-cl
git pull
rm -Rf build
./install.sh
```

and run install-debs again

**Comment by eneskemalergin** [comment]
Actually run install-debs first :)

**Comment by hughperkins** [comment]
well, you need to do the `git pull`, before running the `install-deps`

**Comment by manugarri** [comment]
hmm ok, gonna pull again and rerun. Fingers crossed!

**Comment by hughperkins** [comment]
So like this should be ok I think:

```
cd ~/torch-cl
git pull
bash install-deps
rm -Rf build
./install.sh
```

**Comment by eneskemalergin** [comment]
It gave a lot of error, I guess but the installation process is completed. 

![screenshot](https://cloud.githubusercontent.com/assets/7672473/15276972/b9082096-1abc-11e6-8047-9bbf327fc5b9.png)

It's working now

Thanks!

**Comment by hughperkins** [comment]
ok.  can you try:

```
luajit -l cltorch -e 'cltorch.test()'
```

and then:

```
luajit -l clnn -e 'clnn.test()'
```

**Comment by eneskemalergin** [comment]
Since I have no OpenCl it's giving an error but No OpenCL-enable devices error, so that's fine.

**Comment by hughperkins** [comment]
Hmmm. ok.

**Comment by hughperkins** [comment]
well, you migh at least check:

```
luajit -l torch -e 'torch.test()'
```

and:

```
luajit -l nn -e 'nn.test()'
```

**Comment by eneskemalergin** [comment]
Problem free!!!!!
![result](https://cloud.githubusercontent.com/assets/7672473/15277146/02d7ef90-1ac1-11e6-9e54-43759dd386a3.png)

Thank you for your help.

**Comment by hughperkins** [comment]
Cool.  Great! :-)

**Comment by manugarri** [comment]
ok, dunno why, but running `./install.sh` as sudo did the trick for me. :)

**Comment by hughperkins** [comment]
> ok, dunno why, but running ./install.sh as sudo did the trick for me. :)

Hmmmm, you shouldnt need to run it as root, but if it's working, I guess it's all good :-)  Note that once you've run it as root once, you will have to run it as root after that, or wipe the directory and reinstall.

**Comment by vatsal12117** [comment]
I followed the instructions on the page and getting the following errors -

vatsal@vatsal-Inspiron-7559:~/torch$ ./install.sh
Prefix set to /home/vatsal/torch/install
Installing Lua version: LUAJIT21
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `tputs'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to`tgoto'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `tgetflag'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to`UP'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `tgetent'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to`tgetnum'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `PC'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to`tgetstr'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `BC'
collect2: error: ld returned 1 exit status
make[2]: **\* [exe/luajit-rocks/luajit-2.1/luajit] Error 1
make[1]: **\* [exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all] Error 2
make: **\* [all] Error 2
./install.sh: line 82: /home/vatsal/torch/install/bin/luarocks: No such file or directory
Installing common Lua packages
./install.sh: line 86: /home/vatsal/torch/install/bin/luarocks: No such file or directory

I am running Ubuntu 16.04 with anaconda2. Please help!

**Comment by hughperkins** [comment]
Can you confirm that you are indeed running from `distro-cl` branch of `distro` repository please?

You can confirm that by provding the output of the following commands:

```
cd ~/torch
git status
git log -n 3 --oneline
```

On my computer, where I have installed `distro-cl` into `~/torch-cl`, the output looks like:

```
~/torch-cl$ git status
On branch distro-cl
Your branch is up-to-date with 'hugh/distro-cl'.
[...]

~/torch-cl$ git log -n 3 --oneline
9da3e6e remember to add test script for cutorch-cltorch clobbering
96bda1a prevent cutorch clobbering cltorch, if d afterwards
fafd384 code highlighting in cltorch readme, and links to cutorch-rtc
```

**Comment by vatsal12117** [comment]
I am trying to install torch and using branch master. I am a newbie so dont really know much.

**Comment by vatsal12117** [comment]
vatsal@vatsal-Inspiron-7559:~/torch$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

**Comment by hughperkins** [comment]
Ah.  Well... can you have a read through the instructions on [distro-cl](https://github.com/hughperkins/distro-cl/) page please, and retry?

By the way, are you targeting:
- cutting-edge/bleeding-edge torch? => you should follow instructions at [https://github.com/torch/distro](https://github.com/torch/distro)
- unofficial stable torch? => [distro-cl](https://github.com/hughperkins/distro-cl/)
- OpenCL Torch? =>  [distro-cl](https://github.com/hughperkins/distro-cl/)

**Comment by vatsal12117** [comment]
I followed the instructions on the link - https://github.com/torch/distro but am getting the same error.

vatsal@vatsal-Inspiron-7559:~/torch$ ./install.sh
Prefix set to /home/vatsal/torch/install
Installing Lua version: LUAJIT21
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `tputs'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to`tgoto'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `tgetflag'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to`UP'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `tgetent'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to`tgetnum'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `PC'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to`tgetstr'
/home/vatsal/anaconda2/lib/libreadline.so: undefined reference to `BC'
collect2: error: ld returned 1 exit status
make[2]: **\* [exe/luajit-rocks/luajit-2.1/luajit] Error 1
make[1]: **\* [exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all] Error 2
make: **\* [all] Error 2
./install.sh: line 82: /home/vatsal/torch/install/bin/luarocks: No such file or directory
Installing common Lua packages
./install.sh: line 86: /home/vatsal/torch/install/bin/luarocks: No such file or directory

**Comment by hughperkins** [comment]
Ok.  Just to be clear, I only support the stable/OpenCL distro at [distro-cl](https://github.com/hughperkins/distro-cl) .  I dont support bleeding-edge distro at [distro](https://github.com/torch/distro)  If you want support for bleeding-edge distro, you should log an issue at https://github.com/torch/distro/issues/new

If you want to install stable/OpenCL distro, ie https://github.com/hughperkins/distro-cl , please follow the instructions at https://github.com/hughperkins/distro-cl , and let me know any issues you encounter.

**Comment by vatsal12117** [comment]
Okay. Thanks for the help!
