### ISSUE TITLE
Thank you and Congrats

### ISSUE THREAD

**Issue by j0el** [hughperkins/distro#29]
This isn't an issue, all worked great.  I am 70 years old, so do not think as quickly as I used to.  But I have been using computers since I hung around at MIT in the mid 1960's.  Being retired, I decided to play around with ML.  I took a bunch of Coursera courses including the Andrew Ng one, and have been muddling my way through Python and Tensorflow.  But I just dumped my old Mac for a new Dell XPS which is great except it has Intel graphics and no CUDA like my Mac had.

Over the last week I have been trying to figure out OpenCL.  I have had to build a number of things because the packaged versions are old and API and such change very frequently.  SO many dependencies and so many had to be built and it was a royal PITA.  People may be very smart, but they are not good at either installation or documentation of installation.  Except you.  Once I got beyond the dependencies I was able to get cltorch running with the opencl backend with no trouble at all due to your great scripts and clear instructions.  Currently I am just playing with various tutorials and the style transfer stuff, but almost everything is working well.  I do have one failing test, but it seems not to matter yet.  I don't have the energy to see what is wrong.

I am going to try my hand at tensorflow-cl and hope I can get back to my original project before I tool this detour which is doing some image classification stuff.

Anyway, just wanted to thank you for providing the torch backend on opencl.  It installed easily for me and seems to be working well.

BTW, I see you are spent time in China.  I lived in Hong Kong for many years and one son is still there, working in southern China.  I spent a lot of time in China from the late 80's until 2000.  I really enjoyed it.

Thanks again for your good work.

**Comment by hughperkins** [comment]
Thanks! :-)
