### ISSUE TITLE
why i still need install cutorch?

### ISSUE THREAD

**Issue by 8ar10der** [hughperkins/distro#50]
I come from https://github.com/jcjohnson/neural-style
I want to use that by opencl with my AMD RX 470.
I use archlinux and I install everything I think needed include: torch7, loadcaffe and your cltorch there.
But appear the error `/home/amao/torch-cl/install/bin/luajit: /home/amao/torch-cl/install/share/lua/5.1/trepl/init.lua:384: module 'cutorch' not found:No LuaRocks module found for cutorch`
I have not any nVidia cards that I can't install cutorch although I install cuda by pacman.
What should I do that can let it work well, I have no idea, Can you help me.

**Comment by 8ar10der** [comment]
I solve it. I am noob sorry.

**Comment by hughperkins** [comment]
Cool :)
