### ISSUE TITLE
we need the torch so we can see

### ISSUE THREAD

**Issue by ghost** [hughperkins/distro#54]
Good luck Hugh, I hope to get Torch7 working so I can test it.

**Comment by ArtificialArchitect** [comment]
GPu isn't really important to me it can run on CPU, I am not a GPU person. But it won't work on Windows very well, but I can not aid you anymore with this problem it is too difficult for me.

**Comment by ArtificialArchitect** [comment]
We still get OpenCL 1.1 with Mesa Open driver on AMD which is fine, with great power comes great responsibilities. But the Torch must stay lit for everyone.

**Comment by ArtificialArchitect** [comment]
I apologize for temporarily knighting you, but I am just worried.

**Comment by ArtificialArchitect** [comment]
Well, it may not be very important really, as I can compile it on Windows. What I want is torch7 to work. Because when you play D&D and you run out of torches, you are doomed.

**Comment by ArtificialArchitect** [comment]
Well after dealing with meltdown zombieload is nothing, it is spectre that will just keep coming back.

**Comment by ArtificialArchitect** [comment]
Torch and Torch7 both succesfully complete test 1, but I am not sure the details of torch or lua enough yet. I do not know why it reports the test in binary in that pattern. But I can see it is working.

**Comment by ArtificialArchitect** [comment]
They are now the Knights who say "Ekke Ekke Ekke Ekke Ptang Zoo Boing!" and must therefore give Arthur a test. Unable to pronounce the new name, Arthur addresses them as "Knights who until recently said 'Ni!'," inquiring as to the nature of the test.

**Comment by ArtificialArchitect** [comment]
I'll be more careful the next time I buy a GPU, I stopped using AMD a while ago but got this stupid card when it was supposed to have been a NVidia.

**Comment by ArtificialArchitect** [comment]
I wanted the AMD to work really bad because it would be a cost effective tool for Neural Networks. But I am not able to do those kinds of miracles. I used AMD alot when I was younger because it was cost effective, and their chips run C faster then light but I take what I get.

**Comment by ArtificialArchitect** [comment]
It's difficult trying to set up your own AI lab. I only have so much of a budget I can spare. The AMD cards would really be nice if the drivers would work, but they burnt it out with mining.

**Comment by ArtificialArchitect** [comment]
Well I got torch7 to work, I can see it has some problems though.

**Comment by ArtificialArchitect** [comment]
I have been unable to get it to operate digitally as I am not familiar with lua yet, but I like the language it is fun.

**Comment by ArtificialArchitect** [comment]
We must learn to coexist.

**Comment by ArtificialArchitect** [comment]
It did work on windows, but it was very painful to get it to compile.

**Comment by ArtificialArchitect** [comment]
I am just another Albert Einstein, but there alot of us now.

**Comment by ArtificialArchitect** [comment]
Well, it certainly has some problems for sure.

**Comment by ArtificialArchitect** [comment]
Sorry I am a technical artist I guess, I am not able to work on the codes in the TH library, alot of parallel processing and just very technical but interesting to look at.

**Comment by ArtificialArchitect** [comment]
Well, I am unable to help either you or the torch project with this, I hope they figure it out.

**Comment by ArtificialArchitect** [comment]
Well those kinds of computations you must be careful, it is physics to me you know but you are translating logic into digital logic which is compiled into those switches that run physically in the machine. So yeah, it is pretty intense stuff.

**Comment by ArtificialArchitect** [comment]
I am a soft machine those calculations are hard and can hurt me.

**Comment by ArtificialArchitect** [comment]
I can see they were playing the wumpus game, which bothers me. The only AI problem I really ever think about is that game, because I try to read the book and at some point I go back to the beginning to read about the game and wonder more about it. There is gold, but it's kind of useless if you get eaten by a wumpus. It is the wumpus that bothers me, because it always seems to get away to another place and put gold. But, this time they gave them a torch.

**Comment by ArtificialArchitect** [comment]
Hmm, well the reason I am talking to you at all is you have torch in your distro. There are other repositories with torch forks, but yours and the others were mostly the same results. So, you have a torch distro in there, but I know nothing more. If it was your intention, then I am leaving as I was not sure you are aware of it or who is running this repo.

**Comment by ArtificialArchitect** [comment]
AI keeps getting more real.
