### ISSUE TITLE
In MacOSX, I met the audio module error.

### ISSUE THREAD

**Issue by bemoregt** [hughperkins/distro#6]
In MacOSX, I met the audio module error.
when I run the test.sh script.

"luajit: module 'audio' not found:"

the others testing is fine to my mac OS X (El Capitan).

Thank you.

**Comment by hughperkins** [comment]
Hi Gromit,

What is `test.sh`?  Where can I find this script?

Can I see the full output (eg via https://gist.github.com) , of running `luarocks install audio`?

**Comment by hughperkins** [comment]
(Note that I tried `luarocks install audio` just now, which worked ok, but I did have to first install into my system sox-dev, and fftw3-dev native libraries)
