### ISSUE TITLE
cltorch.test() test_blas fails- OpenCL device version insufficient

### ISSUE THREAD

**Issue by AndrewSmart** [hughperkins/distro#7]
My GPU supports OpenCL 1.0, and I was led to believe cltorch would work on it due to both the distro-cl and cltorch project home pages said under the requirements "an OpenCL capable GPU".

Test output:

```
Completed 222 asserts in 116 tests with 1 errors    

--------------------------------------------------------------------------------    
test_blas
 Function call failed 
clblasSgemm() failed with -48 at /home/crunchbang/dev/torch-cl/opencl/cltorch/src/lib/THClBlas.cpp:429
stack traceback:
    [C]: at 0x7fd794450950
    [C]: in function 'mm'
      ...v/torch-cl/install/share/lua/5.1/cltorch/unit_tensor.lua:421: in function 'v'
      ...v/torch-cl/install/share/lua/5.1/cltorch/unit_tensor.lua:1029: in function <...v/torch-cl/install/share/lua/5.1/cltorch/unit_tensor.lua:1027>
    [C]: in function 'xpcall'
      ...bang/dev/torch-cl/install/share/lua/5.1/torch/Tester.lua:115: in function 'pcall'
      ...bang/dev/torch-cl/install/share/lua/5.1/torch/Tester.lua:186: in function '_run'
      ...bang/dev/torch-cl/install/share/lua/5.1/torch/Tester.lua:161: in function 'run'
      ...v/torch-cl/install/share/lua/5.1/cltorch/unit_tensor.lua:1039: in function 'test'
      ...bang/dev/torch-cl/install/share/lua/5.1/cltorch/Test.lua:15: in function 'f'
    [string "local f = function() return cltorch.test() en..."]:1: in main chunk
      [C]: in function 'xpcall'
      ...hbang/dev/torch-cl/install/share/lua/5.1/itorch/main.lua:209: in function <...hbang/dev/torch-cl/install/share/lua/5.1/itorch/main.lua:173>
    ...hbang/dev/torch-cl/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
      ...ng/dev/torch-cl/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
    ...ng/dev/torch-cl/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
    ...ng/dev/torch-cl/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
    ...hbang/dev/torch-cl/install/share/lua/5.1/itorch/main.lua:381: in main chunk
    [C]: in function 'require'
    (command line):1: in main chunk
    [C]: at 0x00405d30

--------------------------------------------------------------------------------    
...bang/dev/torch-cl/install/share/lua/5.1/cltorch/Test.lua:16: assertion failed!
stack traceback:
    [C]: in function 'assert'
    ...bang/dev/torch-cl/install/share/lua/5.1/cltorch/Test.lua:16: in function 'f'
    [string "local f = function() return cltorch.test() en..."]:1: in main chunk
    [C]: in function 'xpcall'
    ...hbang/dev/torch-cl/install/share/lua/5.1/itorch/main.lua:209: in function <...hbang/dev/torch-cl/install/share/lua/5.1/itorch/main.lua:173>
    ...hbang/dev/torch-cl/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
    ...ng/dev/torch-cl/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
    ...ng/dev/torch-cl/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
    ...ng/dev/torch-cl/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
    ...hbang/dev/torch-cl/install/share/lua/5.1/itorch/main.lua:381: in main chunk
    [C]: in function 'require'
    (command line):1: in main chunk
    [C]: at 0x00405d30
```

clinfo output:
https://gist.github.com/AndrewSmart/c4e236e860321985b983eea5c2a737ea

I saw [cltorch.test() fails at test_blas](https://github.com/hughperkins/cltorch/issues/30) where Hugh said this:

> Hi Joshua, it looks like your GPU is OpenCL 1.0, but cltorch only supports OpenCL 1.1 or higher.

Also saw this [test_blas error on distro-cl](https://github.com/hughperkins/distro-cl/issues/4).

I saw a claim that [clBLAS requires OpenCL 1.2](https://github.com/arrayfire/arrayfire/issues/1316#issuecomment-194681409) (but I couldn't see that requirement on their home page or anywhere else).

Could you please add OpenCL 1.1 or 1.2 is required on the project pages? Or should this be more of a feature matrix thing since it was only clblasSgemm (mm) that fails (a*b failed too but a:mul(b) worked)? I can fill out the tables for what OpenCL 1.0 does not work. I'd offer to do PRs but I don't know if it is 1.1 or 1.2 that is required.

P.S. clnn.test() gave many more errors, these 18 of 74 tests failed with -48 & -49 OpenCL errors:
SpatialAveragePooling_backward
SpatialAveragePooling_backward_batch
SpatialAveragePooling_backward_batch_ceil
SpatialAveragePooling_backward_ceil
SpatialConvolutionMM_backward_batch
SpatialConvolutionMM_backward_single
SpatialConvolutionMM_forward_1d_byhand
SpatialConvolutionMM_forward_batch
SpatialConvolutionMM_forward_single
SpatialConvolutionMM_forward_single_padded
SpatialConvolutionMM_forward_single_vgglayer13
SpatialMaxPooling_backward
SpatialMaxPooling_backward_batch
SpatialMaxPooling_backward_batch_ceil
SpatialMaxPooling_backward_ceil
TemporalConvolution2_backward_gradInput
TemporalConvolution2_backward_gradParams
TemporalConvolution2_forward

Thanks!

**Comment by hughperkins** [comment]
Fair enough.  Updated the readme.

**Comment by hughperkins** [comment]
> Could you please add OpenCL 1.1 or 1.2 is required on the project pages? Or should this be more of a feature matrix thing since it was only clblasSgemm (mm) that fails (a*b failed too but a:mul(b) worked)? I can fill out the tables for what OpenCL 1.0 does not work. I'd offer to do PRs but I don't know if it is 1.1 or 1.2 that is required.

Yes, so, as you correclty pointed out clblas needs 1.2.

I'm very much for migrating to use either [clBLAST](https://github.com/CNugteren/CLBlast) or [libdnn](https://github.com/naibaf7/libdnn) (the latter actually would be implementation at the convolution endpoint, using implicit gemm algorithm, whereas the former would replace clblas, as a blas implementation, but ocntinue to use im2col convolutions.

I think the requirements of both of these libraries is a bit harder in terms of c++ version (both need c++11), but might be fractionally softer in terms of OpenCL version (though, 1.0 is pushing it a bit I would think, you could check).

If you want to submit a PR, to migrate to either of these, very welcome.  Migrating to clblast is probably more straightforward on the whole.  Migrating to libdnn might give faster convolutions.  In either case, I'd hope to see some performance comparison before/after, eg using VGG and/or alexnet, ideally.  I imagine either of them will be faster, but better to check.  And then you can put on your cv 'migrated opencl torch from clblas to clblast, improving performacne on alexnet by 3 times' or whatever :-)
