### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by NoskcajXela** [hughperkins/distro#9]
First off let me say that I'm attempting to run all this off of an 8GB usb, which could be part of the problem (I have been missing commands and having to download them).
The command terminal gives me:

CMake Error at /usr/share/cmake-3.5/Modules/CMakeDetermineCCompiler.cmake:57 (message):
  Could not find compiler set in environment variable CC:

  gcc-4.9.
Call Stack (most recent call first):
  CMakeLists.txt

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

I've tried looking it up, perhaps I don't have mingw, which I have no idea how to install.

**Comment by hughperkins** [comment]
Hi DarkTachyon,

Can you clarify as much about your system as possible?  It sounds like you are buliding on Windows?

**Comment by NoskcajXela** [comment]
I'm working on a USB drive that has windows normally running off of it.

If you want the specs, I have an Intel core i5 6600k, and a AMD R9 390.

**Comment by hughperkins** [comment]
Ok.  I dont have the resources to support Windows personally at this time, for distro-cl.  There is however a Windows-build thread in process at https://github.com/torch/torch7/pull/287#issuecomment-239082781 , and a very draft wiki page (just copy and pasted from this thread for now .... ) at https://github.com/torch/torch7/wiki/Windows  Can you first confirm you can/cant install standard torch, following the instructions in this thread/page?

**Comment by NoskcajXela** [comment]
The main reason I don't want to install regular torch is because I want to
make full use of my system. If I install regular torch, it won't support my
AMD card.

Also I am still running Linux. I boot from the USB itself meningitis that
there should be no connection to windows.

**Comment by hughperkins** [comment]
Ah.  well, running linux off a usb key should not be an issue.  I've tested running torch-cl on ubuntu 16.04 installed to a usb key, and it works ok.  Can you confirm that you've done a standard ubuntu 16.04 installation to the usbkey?  ie, something like:

Given:
- two usb keys:
  - one to contain the installer, we'll call it the 'installer key'
  - one to contain the installation, we'll call it the 'target key'

When:
- I use some means to install the ubuntu 16.04 installer to the installer key
- boot from the installer key
- use the installer key to install ubuntu 16.04 to the target key
- boot from the target key (which is now just standard ubuntu 16.04 installation)
- install distro-cl

Then:
- distro-cl works ok for me :-)
